### ISSUE TITLE
new version

### ISSUE THREAD

**Issue by jimmymjing** [DigitalStrawberry/ANE-Amplitude#2]
Hello, this ANE works great. Could you please update it to the latest version? Thanks so much!

**Comment by marpies** [comment]
Hi,

We've updated the SDKs, see [v1.1.2 release](https://github.com/DigitalStrawberry/ANE-Amplitude/releases/tag/v1.1.2). Note you need to use AIR 28+ or provide iOS 11+ SDK when packaging your IPA.

**Comment by jimmymjing** [comment]
Thanks! I will give it a try.
