### ISSUE TITLE
version 4.4.0

### ISSUE THREAD

**Issue by jimmymjing** [DigitalStrawberry/ANE-Amplitude#3]
Hi, could you please update the version to 4.4.0. I see that adding ability to set group properties is available. Thanks so much!

**Comment by marpies** [comment]
Hi,

We've updated the SDKs and added new APIs in [v1.2.0](https://github.com/DigitalStrawberry/ANE-Amplitude/releases/tag/v1.2.0), see the [README for sample code](https://github.com/DigitalStrawberry/ANE-Amplitude#set-group).

**Comment by jimmymjing** [comment]
Thanks so much! Will try it out right away
