### ISSUE TITLE
revenueType and eventProperties are missing

### ISSUE THREAD

**Issue by denmorgenshtern** [DigitalStrawberry/ANE-Amplitude#4]
Hello @marpies Marcel!
How are you? :)

Can you please update the ANE and implement a full list of revenue tracking fields and methods? 
revenueType and eventProperties are missing.

https://help.amplitude.com/hc/en-us/articles/115002935588#tracking-revenue
https://help.amplitude.com/hc/en-us/articles/115002278527#tracking-revenue

**Comment by marpies** [comment]
Hello Denis,

Thanks for the report, we will add support for the additional fields.

**Comment by denmorgenshtern** [comment]
Great, thanks!

**Comment by marpies** [comment]
Hi @denmorgenshtern,

The `logRevenue` method now accepts `revenueType` and `eventProperties` arguments.

**Comment by denmorgenshtern** [comment]
Thank you for the quick fix!
