### ISSUE TITLE
stopped receiving any logs

### ISSUE THREAD

**Issue by jimmymjing** [DigitalStrawberry/ANE-Amplitude#6]
Hello, I just realized that my amplitude stopped receiving any logs from my game. Is it possible to upgrade the ANE, please? Thanks!

**Comment by jimmymjing** [comment]
Hello, I tried everything I could but it's still not receiving any log events. The last log event that I got was on July 12th... Do you use this ANE as well? Could you please tell me if you have any issues with it? Thanks so much!
p.s. I even updated the iOS SDK to the latest, but got no luck.

**Comment by marpies** [comment]
Hi,

We're using the ANE as well and continue to receive logs correctly. Maybe you could try contacting Amplitude to see if there's no issue with your account.

**Comment by jimmymjing** [comment]
Hello, I even created a new Amplitude account but still not receiving any logs. I think I stopped receiving any logs since I have upgraded my AIR SDK to AIR 33.1.1.190. (just my assumption by the released date...) May I ask if you are using the same SDK with license? Thank you!

**Comment by marpies** [comment]
We are not using AIR 33 yet so that could be the issue.

**Comment by jimmymjing** [comment]
Oh... AIR 33.1.1.176 works though. Will you take a look at it, or I shall report it to Harman? But I don't think they will track it down as I have no idea how to describe this issue...

**Comment by marpies** [comment]
Do you see any issues when making URL requests using AIR API with the latest SDK? For example when trying to load your own server resources inside the app? Would you be able to test this?

It should be reported to Harman as it's unlikely we'll be able to fix this within the ANE scope. If it is not reproducible using AIR API only, `let them know that NSURLSession requests on iOS seem to be failing in the latest SDK (while working in previous build) and refer them to Amplitude iOS SDK as a reference.

**Comment by jimmymjing** [comment]
I have no problem with URL requests, FYI, the Bugsee ANE works just fine.

**Comment by jimmymjing** [comment]
God...I still haven't got any feedback after 1 week from Harman which really makes me nervous. One more question, when will you probably have time to upgrade to the latest version? I really need Amplitude to track the data...

**Comment by marpies** [comment]
I just tested AIR 33.1.1.217 with Amplitude ANE in a sample app and events are showing up correctly in the Amplitude dashboard, so it doesn't seem to be related to the newer AIR SDK.

**Comment by jimmymjing** [comment]
Thanks for your time! Is there a way to view the log? maybe there's a conflict with some ANEs that I have?

**Comment by marpies** [comment]
You could try using the Console app in macOS to see device logs (when your IPA is built using one of the `ipa-debug` targets).

Alternatively you may try going back in your commit history and see where the Amplitude logging broke.
